### ISSUE TITLE
Upgrade to support v3 and pro

### ISSUE THREAD

**Issue by ricpar11** [samihaddad/dart-fingerprintjs#5]
Hello, first of all thanks for this awesome package 💯 

This package does not support the current stable version of fingerprintjs (v3), also there's no way to set the token to enable pro version.

**Comment by samihaddad** [comment]
Hello, I'm glad you like it.
I will have to look into v3 and the API changes. Would it work for you to have the token in the current version? @ricpar11

**Comment by ricpar11** [comment]
I would be perfect! Thanks @samihaddad

**Comment by samihaddad** [comment]
It seems passing the token works independently using a script, did you try this https://dev.fingerprintjs.com/v2/docs/js-agent#automatic-mode-available-only-in-cdn-version @ricpar11

**Comment by ricpar11** [comment]
I will give it a try! thanks again
